apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llm-service
  namepsace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/crummycrushed/ops-manifests
    targetVersion: main 
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: llm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true