apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: llm-service
  namespace: llm
spec:
  replicas: 2
  strategy:
    blueGreen:
      activeService: llm-service
      previewService: llm-service-preview
  selector:
    matchLabels:
      app: llm-service
  template:
    metadata:
      labels:
        app: llm-service
    spec:
      containers:
        - name: llm-service
          image: crummycrushed/ops-service:a593e71cc7f1a849256a49fdb9735f591c14ed73
          ports:
            - containerPort: 8000
          env: 
            - name : OLLAMA_HOST
              value: "ollama"
            - name: OLLAMA_PORT
              value: "11434"
          livelinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet: 
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: logs
              mountPath: /app/logs
      volumes:
        - name: logs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: llm-service
  namespace: llm
spec:
  selector:
    app: llm-service
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: llm-service-preview
  namespace: llm
spec:
  selector:
    app: llm-service
  ports:
  - port: 80
    targetPort: 8080

